"""Доабвление ноавх таблиц

Revision ID: 18eb460c72da
Revises: 298b9269ae97
Create Date: 2024-10-12 15:31:51.082395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18eb460c72da'
down_revision: Union[str, None] = '298b9269ae97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('department_settings',
    sa.Column('department_id', sa.String(), nullable=False),
    sa.Column('max_photo_count', sa.Integer(), nullable=True),
    sa.Column('max_divice_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('department_id')
    )
    op.create_index(op.f('ix_department_settings_department_id'), 'department_settings', ['department_id'], unique=False)
    op.create_table('devises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=True),
    sa.Column('department', sa.String(), nullable=True),
    sa.Column('modify_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_devises_admin_id'), 'devises', ['admin_id'], unique=False)
    op.create_index(op.f('ix_devises_department'), 'devises', ['department'], unique=False)
    op.create_index(op.f('ix_devises_id'), 'devises', ['id'], unique=False)
    op.add_column('admins', sa.Column('role', sa.String(), nullable=True))
    op.create_index(op.f('ix_admins_role'), 'admins', ['role'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_role'), table_name='admins')
    op.drop_column('admins', 'role')
    op.drop_index(op.f('ix_devises_id'), table_name='devises')
    op.drop_index(op.f('ix_devises_department'), table_name='devises')
    op.drop_index(op.f('ix_devises_admin_id'), table_name='devises')
    op.drop_table('devises')
    op.drop_index(op.f('ix_department_settings_department_id'), table_name='department_settings')
    op.drop_table('department_settings')
    # ### end Alembic commands ###
