"""Initial migration

Revision ID: b0c7bda30b2e
Revises: 507712318771
Create Date: 2024-06-16 21:29:27.823119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0c7bda30b2e'
down_revision: Union[str, None] = '507712318771'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_admins_login', table_name='admins')
    op.create_index(op.f('ix_admins_login'), 'admins', ['login'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_login'), table_name='admins')
    op.create_index('ix_admins_login', 'admins', ['login'], unique=False)
    # ### end Alembic commands ###
