"""добавил таблицу логов

Revision ID: b865fdbdb1ce
Revises: 18eb460c72da
Create Date: 2024-10-30 13:34:12.627417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b865fdbdb1ce'
down_revision: Union[str, None] = '18eb460c72da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('log_confirm',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guide', sa.String(), nullable=True),
    sa.Column('devise_guid', sa.String(), nullable=True),
    sa.Column('department_id', sa.String(), nullable=True),
    sa.Column('inout', sa.String(), nullable=True),
    sa.Column('response', sa.String(), nullable=True),
    sa.Column('json_data', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_confirm_department_id'), 'log_confirm', ['department_id'], unique=False)
    op.create_index(op.f('ix_log_confirm_devise_guid'), 'log_confirm', ['devise_guid'], unique=False)
    op.create_index(op.f('ix_log_confirm_guide'), 'log_confirm', ['guide'], unique=False)
    op.create_index(op.f('ix_log_confirm_id'), 'log_confirm', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_log_confirm_id'), table_name='log_confirm')
    op.drop_index(op.f('ix_log_confirm_guide'), table_name='log_confirm')
    op.drop_index(op.f('ix_log_confirm_devise_guid'), table_name='log_confirm')
    op.drop_index(op.f('ix_log_confirm_department_id'), table_name='log_confirm')
    op.drop_table('log_confirm')
    # ### end Alembic commands ###
