"""Initial migration

Revision ID: 507712318771
Revises: dc41dd8f5907
Create Date: 2024-06-16 20:52:23.796167

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '507712318771'
down_revision: Union[str, None] = 'dc41dd8f5907'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('login', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_id'), 'admins', ['id'], unique=False)
    op.create_index(op.f('ix_admins_login'), 'admins', ['login'], unique=False)
    op.create_index(op.f('ix_admins_name'), 'admins', ['name'], unique=False)
    op.create_index(op.f('ix_admins_password'), 'admins', ['password'], unique=False)
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.drop_index('ix_users_email', table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), nullable=True))
    op.create_index('ix_users_email', 'users', ['email'], unique=1)
    op.drop_column('users', 'created_at')
    op.drop_index(op.f('ix_admins_password'), table_name='admins')
    op.drop_index(op.f('ix_admins_name'), table_name='admins')
    op.drop_index(op.f('ix_admins_login'), table_name='admins')
    op.drop_index(op.f('ix_admins_id'), table_name='admins')
    op.drop_table('admins')
    # ### end Alembic commands ###
